<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Krzak">

<title>Rtutorial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Rtutorial_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rtutorial_files/libs/quarto-html/quarto.js"></script>
<script src="Rtutorial_files/libs/quarto-html/popper.min.js"></script>
<script src="Rtutorial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rtutorial_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rtutorial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rtutorial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rtutorial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rtutorial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rtutorial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rtutorial</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Krzak </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="week3-introduction-to-r-toolkit" class="level2">
<h2 class="anchored" data-anchor-id="week3-introduction-to-r-toolkit">Week3: Introduction to R Toolkit</h2>
<p>This activity is prepared to warm-up your understanding of LA workflow. Through this exercise, we will practice basics of how RStudio works. In all of our practices, we will follow the LA workflow.</p>
<ol type="1">
<li><strong>Prepare:</strong> We will import our data file into R in the “Prepare” section.</li>
<li><strong>Wrangle:</strong> We will prepare and wrangle our data in the “Wrangle” section.</li>
<li><strong>Explore:</strong> We will check the patterns in the data through visualization.</li>
<li><strong>Model:</strong> We will run a regression model in the “Model” section.</li>
<li><strong>Communicate:</strong> Create a reproducible report of your work, you can share with others in the “Communicate” section.</li>
</ol>
</section>
<section id="how-to-follow-this-document" class="level2">
<h2 class="anchored" data-anchor-id="how-to-follow-this-document">How to follow this document?</h2>
<p>In the R tutorial toolkit and case study week, we will be using a <strong>quarto</strong> markdown file, the extension of the file is “.qmd”. Unlike R markdown, Quarto documents are fully reproducible and support dozens of output formats, like PDFs, Word files, presentations, and more. In this document, you will see, we’re using visual mode to see the general parts.</p>
<p>There are two keys to your use of Quarto for this activity:</p>
<ol type="1">
<li>First, you can see the document in the “Visual Editor” mode. You can use this mode by clicking the word “Visual” on the left side of the toolbar above. The visual editor allows you to view formatted headers, text and code chunks as specified by the underlying markdown syntax, or “Source” text. Visual mode is a bit more “human readable” than syntax but definitely take a look at the source text.</li>
<li>Second, note the specially formatted text box below called a “code chunck.” These chuncks allows you to run code from multiple languages including R, Python, and SQL. This specific code chunck contains a line of R code. If you wonder other chunck options, you can visit this <a href="https://yihui.org/knitr/options/" title="Chunk options">link</a> and learn more about it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"Img/research-workflow.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Img/research-workflow.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="the-data-intensive-research-workflow" class="level2">
<h2 class="anchored" data-anchor-id="the-data-intensive-research-workflow">The Data-Intensive Research Workflow</h2>
<p>Last week, in the class, we talked about the data-intensive research workflow.As we mentioned a couple of times, we will follow this workflow to present our research approach.</p>
<p>Let’s get started.</p>
</section>
<section id="prepare" class="level2">
<h2 class="anchored" data-anchor-id="prepare">1. Prepare</h2>
<p>As a first step in the data-intensive research workflow, we will need to define our research question(s) and need to understand where the data comes from (Krumm, 2018).</p>
<p>For this work, we will work with data come from an unpublished research study, which utilized a number of different data sources to understand high school students’ motivation within the context of online courses.</p>
<section id="our-research-question-is" class="level3">
<h3 class="anchored" data-anchor-id="our-research-question-is"><strong>Our research question is:</strong></h3>
<p>“Is there a relationship between the time students spend on a course and their final course grade?”</p>
<p>For our analysis, we will need certain packages.One of the most common package is “Tidyverse” package. This package is actually a collection of R packages designed for wrangling and exploring data and which all share an underlying design philosophy, grammar, and data structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"Img/tidyverse.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Img/tidyverse.png" class="img-fluid"></p>
</div>
</div>
<p>Through this class, we will have a chance to try different libraries in the tidyverse package. Let’s install our tidyverse package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We installed the package, what do we need to do now for using this package?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<p>We will also use another package called “skimr”. This is a handy package that provides summary statistics that you can skim quickly to understand your data. We’ll be using this later in the Explore section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install the {skimr} package below.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"skimr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load the {skimr} package below.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-or-reading-in-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-or-reading-in-data"><strong>Loading (or reading in) data</strong></h3>
<p>The data we’ll explore in this class were originally collected for a unpublished research study and utilized a number of different data sources to understand students’ course related motivation. These courses were designed and taught by instructors through a state-wide online course provider designed to supplement-but not replace-students’ enrollment in their local school.</p>
<p>The data used in this case study has already been “wrangled” quite a bit, but the original datasets included:</p>
<ol type="1">
<li>A self-report survey assessing the three aspects of students’ motivation.</li>
<li>Log-trace data, such as data output from the learning management system (LMS).</li>
<li>Discussion board data</li>
<li>Academic achievement data</li>
</ol>
<p>If you are more interested in learning more about these datasets, you can visit Chapter 7 from your book, Data Science in Education Using R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load the sci-online-classes.cvs data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sci_data<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"Data/sci-online-classes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 603 Columns: 30
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): course_id, subject, semester, section, Gradebook_Item, Gender
dbl (23): student_id, total_points_possible, total_points_earned, percentage...
lgl  (1): Grade_Category

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="your-turn" class="level4">
<h4 class="anchored" data-anchor-id="your-turn"><u><strong>Your Turn:</strong></u></h4>
<p>Why do you think we included data/ before our sci-online-classes.csv file? Why quotation marks?</p>
<p>Add your responses after the dashes below:</p>
<ul>
<li>Your response here</li>
</ul>
<p>Hint: check the files panel.</p>
</section>
</section>
<section id="viewing-or-inspecting-data" class="level3">
<h3 class="anchored" data-anchor-id="viewing-or-inspecting-data"><strong>Viewing or inspecting data</strong></h3>
<p>Let’s quickly check our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(sci_data)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sci_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 30
   student_id course_id     total_points_possible total_points_earned
        &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;               &lt;dbl&gt;
 1      43146 FrScA-S216-02                  3280                2220
 2      44638 OcnA-S116-01                   3531                2672
 3      47448 FrScA-S216-01                  2870                1897
 4      47979 OcnA-S216-01                   4562                3090
 5      48797 PhysA-S116-01                  2207                1910
 6      51943 FrScA-S216-03                  4208                3596
 7      52326 AnPhA-S216-01                  4325                2255
 8      52446 PhysA-S116-01                  2086                1719
 9      53447 FrScA-S116-01                  4655                3149
10      53475 FrScA-S116-02                  1710                1402
# ℹ 593 more rows
# ℹ 26 more variables: percentage_earned &lt;dbl&gt;, subject &lt;chr&gt;, semester &lt;chr&gt;,
#   section &lt;chr&gt;, Gradebook_Item &lt;chr&gt;, Grade_Category &lt;lgl&gt;,
#   FinalGradeCEMS &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, Points_Earned &lt;dbl&gt;,
#   Gender &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;,
#   q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, TimeSpent &lt;dbl&gt;,
#   TimeSpent_hours &lt;dbl&gt;, TimeSpent_std &lt;dbl&gt;, int &lt;dbl&gt;, pc &lt;dbl&gt;, uv &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="your-turn-1" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-1"><u><strong>Your Turn:</strong></u></h4>
<p>What do you notice about this dataset? What do you wonder? Add one or two thoughts after the dash below:</p>
<ul>
<li>I notice there is way more data then I could reasonably examine without tools. There are also some variables with unclear definitions. like PV, and UV. I’m curious what those mean. I am also curious if time spent studying had more of an impact in some courses compared to others.</li>
</ul>
<p>There are other ways to inspect your data; the glimpse() function provides one such way. Let’s take a glimpse at our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(sci_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 603
Columns: 30
$ student_id            &lt;dbl&gt; 43146, 44638, 47448, 47979, 48797, 51943, 52326,…
$ course_id             &lt;chr&gt; "FrScA-S216-02", "OcnA-S116-01", "FrScA-S216-01"…
$ total_points_possible &lt;dbl&gt; 3280, 3531, 2870, 4562, 2207, 4208, 4325, 2086, …
$ total_points_earned   &lt;dbl&gt; 2220, 2672, 1897, 3090, 1910, 3596, 2255, 1719, …
$ percentage_earned     &lt;dbl&gt; 0.6768293, 0.7567261, 0.6609756, 0.6773345, 0.86…
$ subject               &lt;chr&gt; "FrScA", "OcnA", "FrScA", "OcnA", "PhysA", "FrSc…
$ semester              &lt;chr&gt; "S216", "S116", "S216", "S216", "S116", "S216", …
$ section               &lt;chr&gt; "02", "01", "01", "01", "01", "03", "01", "01", …
$ Gradebook_Item        &lt;chr&gt; "POINTS EARNED &amp; TOTAL COURSE POINTS", "ATTEMPTE…
$ Grade_Category        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ FinalGradeCEMS        &lt;dbl&gt; 93.45372, 81.70184, 88.48758, 81.85260, 84.00000…
$ Points_Possible       &lt;dbl&gt; 5, 10, 10, 5, 438, 5, 10, 10, 443, 5, 12, 10, 5,…
$ Points_Earned         &lt;dbl&gt; NA, 10.00, NA, 4.00, 399.00, NA, NA, 10.00, 425.…
$ Gender                &lt;chr&gt; "M", "F", "M", "M", "F", "F", "M", "F", "F", "M"…
$ q1                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 4, 3, 5, NA,…
$ q2                    &lt;dbl&gt; 4, 4, 4, 5, 3, NA, 5, 3, 3, NA, NA, 5, 3, 3, NA,…
$ q3                    &lt;dbl&gt; 4, 3, 4, 3, 3, NA, 3, 3, 3, NA, NA, 3, 3, 5, NA,…
$ q4                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 5, 3, 5, NA,…
$ q5                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 5, 4, 5, NA,…
$ q6                    &lt;dbl&gt; 5, 4, 4, 5, 4, NA, 5, 4, 3, NA, NA, 5, 3, 5, NA,…
$ q7                    &lt;dbl&gt; 5, 4, 4, 4, 4, NA, 4, 3, 3, NA, NA, 5, 3, 5, NA,…
$ q8                    &lt;dbl&gt; 5, 5, 5, 5, 4, NA, 5, 3, 4, NA, NA, 4, 3, 5, NA,…
$ q9                    &lt;dbl&gt; 4, 4, 3, 5, NA, NA, 5, 3, 2, NA, NA, 5, 2, 2, NA…
$ q10                   &lt;dbl&gt; 5, 4, 5, 5, 3, NA, 5, 3, 5, NA, NA, 4, 4, 5, NA,…
$ TimeSpent             &lt;dbl&gt; 1555.1667, 1382.7001, 860.4335, 1598.6166, 1481.…
$ TimeSpent_hours       &lt;dbl&gt; 25.91944500, 23.04500167, 14.34055833, 26.643610…
$ TimeSpent_std         &lt;dbl&gt; -0.18051496, -0.30780313, -0.69325954, -0.148446…
$ int                   &lt;dbl&gt; 5.0, 4.2, 5.0, 5.0, 3.8, 4.6, 5.0, 3.0, 4.2, NA,…
$ pc                    &lt;dbl&gt; 4.50, 3.50, 4.00, 3.50, 3.50, 4.00, 3.50, 3.00, …
$ uv                    &lt;dbl&gt; 4.333333, 4.000000, 3.666667, 5.000000, 3.500000…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sci_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 30
  student_id course_id     total_points_possible total_points_earned
       &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;               &lt;dbl&gt;
1      43146 FrScA-S216-02                  3280                2220
2      44638 OcnA-S116-01                   3531                2672
3      47448 FrScA-S216-01                  2870                1897
4      47979 OcnA-S216-01                   4562                3090
5      48797 PhysA-S116-01                  2207                1910
6      51943 FrScA-S216-03                  4208                3596
# ℹ 26 more variables: percentage_earned &lt;dbl&gt;, subject &lt;chr&gt;, semester &lt;chr&gt;,
#   section &lt;chr&gt;, Gradebook_Item &lt;chr&gt;, Grade_Category &lt;lgl&gt;,
#   FinalGradeCEMS &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, Points_Earned &lt;dbl&gt;,
#   Gender &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;,
#   q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, TimeSpent &lt;dbl&gt;,
#   TimeSpent_hours &lt;dbl&gt;, TimeSpent_std &lt;dbl&gt;, int &lt;dbl&gt;, pc &lt;dbl&gt;, uv &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(sci_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 30
  student_id course_id     total_points_possible total_points_earned
       &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;               &lt;dbl&gt;
1      97150 PhysA-S216-01                  2710                1803
2      97265 PhysA-S216-01                  3101                2078
3      97272 OcnA-S216-01                   2872                1733
4      97374 BioA-S216-01                   8586                6978
5      97386 BioA-S216-01                   2761                1937
6      97441 FrScA-S216-02                  2607                2205
# ℹ 26 more variables: percentage_earned &lt;dbl&gt;, subject &lt;chr&gt;, semester &lt;chr&gt;,
#   section &lt;chr&gt;, Gradebook_Item &lt;chr&gt;, Grade_Category &lt;lgl&gt;,
#   FinalGradeCEMS &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, Points_Earned &lt;dbl&gt;,
#   Gender &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;,
#   q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, TimeSpent &lt;dbl&gt;,
#   TimeSpent_hours &lt;dbl&gt;, TimeSpent_std &lt;dbl&gt;, int &lt;dbl&gt;, pc &lt;dbl&gt;, uv &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Generally, rows typically represent “cases”, the units that we measure, or the units on which we collect data. What counts as a “case” (and therefore what is represented as a row) varies by (and within) fields. There may be multiple types or levels of units studied in your field; listing more than one is fine! Also, please consider what columns-which usually represent variables-represent in your area of work and/or research.</p>
</section>
<section id="your-turn-2" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-2"><u><strong>Your Turn:</strong></u></h4>
<p>How many “cases” or observations are in this dataset?</p>
<ul>
<li>There are 603 observations</li>
</ul>
<p>Pick two columns (or more) and write what you think it represents:</p>
<ul>
<li>Percentage earned tells us what percent of the possible points were earned by a student in decimal format. Student_id identifies the student who took the course and course_id represents which course they took.</li>
</ul>
</section>
</section>
</section>
<section id="wrangle" class="level2">
<h2 class="anchored" data-anchor-id="wrangle">2. Wrangle</h2>
<p>By wrangle, we refer to the process of cleaning and processing data, and, in some cases, merging (or joining) data from multiple sources. Often, this part of the process is very time-intensive! Wrangling your data into shape can itself be an important accomplishment! And documenting your code using R scripts or Markdown files will save yourself and others a great deal of time wrangling data in the future! There are great tools in R for data wrangling, especially through the use of {dplyr} R package which is part of the tidyverse.</p>
<section id="selecting-variables" class="level3">
<h3 class="anchored" data-anchor-id="selecting-variables">Selecting Variables</h3>
<p>Remember our research question, what we were interested in finding about this data?</p>
<p>Let’s practice selecting a few variables by introducing <strong>pipe</strong> operator, |&gt;. Pipes are a powerful tool for combining a sequence of functions or processes.</p>
<p>Run the following code chunck to “pipe” our sci_data to the select() function include the following two variables as arguments:</p>
<ul>
<li><p>FinalGradeCEMS (i.e., students’ final grades on a 0-100 point scale)</p></li>
<li><p>TimeSpent (i.e., the number of minutes they spent in the course’s learning management system)</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(FinalGradeCEMS,TimeSpent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 2
   FinalGradeCEMS TimeSpent
            &lt;dbl&gt;     &lt;dbl&gt;
 1           93.5   1555.  
 2           81.7   1383.  
 3           88.5    860.  
 4           81.9   1599.  
 5           84     1482.  
 6           NA        3.45
 7           83.6   1322.  
 8           97.8   1390.  
 9           96.1   1479.  
10           NA       NA   
# ℹ 593 more rows</code></pre>
</div>
</div>
<p>Notice how the number of columns (variables) is now different! Let’s check our data with View() function this time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(sci_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>A quick footnote about pipes:</strong> The original pipe operator, %&gt;%, comes from the <a href="https://magrittr.tidyverse.org/">{magrittr}</a> package but all packages in the tidyverse load %&gt;% for you automatically, so you don’t usually load magrittr explicitly. The pipe has become such a useful and much used operator in R that it is now baked into R using the new and simpler native pipe |&gt; operator. You can use both fairly interchangeably but there are a <a href="https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/">few differences between pipe operators</a>.</p>
</section>
<section id="filtering-variables" class="level3">
<h3 class="anchored" data-anchor-id="filtering-variables">Filtering Variables</h3>
<p>Let’s exploring filtering variables. We will filter our data to view only the rows associated with students who earned a final grade (as a percentage) of 70 or 70% or higher.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(FinalGradeCEMS<span class="sc">&gt;</span><span class="dv">70</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 438 × 30
   student_id course_id     total_points_possible total_points_earned
        &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;               &lt;dbl&gt;
 1      43146 FrScA-S216-02                  3280                2220
 2      44638 OcnA-S116-01                   3531                2672
 3      47448 FrScA-S216-01                  2870                1897
 4      47979 OcnA-S216-01                   4562                3090
 5      48797 PhysA-S116-01                  2207                1910
 6      52326 AnPhA-S216-01                  4325                2255
 7      52446 PhysA-S116-01                  2086                1719
 8      53447 FrScA-S116-01                  4655                3149
 9      53475 FrScA-S216-01                  1209                 977
10      54066 OcnA-S116-01                   4641                3429
# ℹ 428 more rows
# ℹ 26 more variables: percentage_earned &lt;dbl&gt;, subject &lt;chr&gt;, semester &lt;chr&gt;,
#   section &lt;chr&gt;, Gradebook_Item &lt;chr&gt;, Grade_Category &lt;lgl&gt;,
#   FinalGradeCEMS &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, Points_Earned &lt;dbl&gt;,
#   Gender &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;,
#   q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, TimeSpent &lt;dbl&gt;,
#   TimeSpent_hours &lt;dbl&gt;, TimeSpent_std &lt;dbl&gt;, int &lt;dbl&gt;, pc &lt;dbl&gt;, uv &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="your-turn-3" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-3"><u><strong>Your Turn:</strong></u></h4>
<p>In the next code chunk, change the cut-off from 70% to some other value-larger or smaller (maybe much larger or smaller) - feel free to play around with the code a bit!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(FinalGradeCEMS<span class="sc">&gt;</span><span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 495 × 30
   student_id course_id     total_points_possible total_points_earned
        &lt;dbl&gt; &lt;chr&gt;                         &lt;dbl&gt;               &lt;dbl&gt;
 1      43146 FrScA-S216-02                  3280                2220
 2      44638 OcnA-S116-01                   3531                2672
 3      47448 FrScA-S216-01                  2870                1897
 4      47979 OcnA-S216-01                   4562                3090
 5      48797 PhysA-S116-01                  2207                1910
 6      52326 AnPhA-S216-01                  4325                2255
 7      52446 PhysA-S116-01                  2086                1719
 8      53447 FrScA-S116-01                  4655                3149
 9      53475 FrScA-S216-01                  1209                 977
10      54066 OcnA-S116-01                   4641                3429
# ℹ 485 more rows
# ℹ 26 more variables: percentage_earned &lt;dbl&gt;, subject &lt;chr&gt;, semester &lt;chr&gt;,
#   section &lt;chr&gt;, Gradebook_Item &lt;chr&gt;, Grade_Category &lt;lgl&gt;,
#   FinalGradeCEMS &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, Points_Earned &lt;dbl&gt;,
#   Gender &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;,
#   q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, TimeSpent &lt;dbl&gt;,
#   TimeSpent_hours &lt;dbl&gt;, TimeSpent_std &lt;dbl&gt;, int &lt;dbl&gt;, pc &lt;dbl&gt;, uv &lt;dbl&gt;</code></pre>
</div>
</div>
<p>What happens when you change the cut-off from 70 to something else?</p>
<ul>
<li>The amount of observations went up from 438 to 495 when I changed the cutoff to 60%</li>
</ul>
</section>
</section>
<section id="arrange" class="level3">
<h3 class="anchored" data-anchor-id="arrange">Arrange</h3>
<p>The last function we’ll use for preparing tables in arrange. We’ll again use the pipe operator to combine this with arrange() function we used already -select(). We do this so we can view only time spent and final grades.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(FinalGradeCEMS,TimeSpent)<span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(FinalGradeCEMS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 2
   FinalGradeCEMS TimeSpent
            &lt;dbl&gt;     &lt;dbl&gt;
 1          0          13.9
 2          0.535     306. 
 3          0.903      88.5
 4          1.80       44.7
 5          2.93       57.7
 6          3.01      571. 
 7          3.06        0.7
 8          3.43      245. 
 9          5.04      202. 
10          5.2        11.0
# ℹ 593 more rows</code></pre>
</div>
</div>
<p>Note that arrange works by sorting values in ascending order (from lowest to highest); you can change this by using the desc() function as an argument with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let's change the order from asc to desc</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(FinalGradeCEMS,TimeSpent)<span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(FinalGradeCEMS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 2
   FinalGradeCEMS TimeSpent
            &lt;dbl&gt;     &lt;dbl&gt;
 1          100       2689.
 2           99.8     2921.
 3           99.3      965.
 4           99.1      879.
 5           99.0     1770.
 6           98.6     1138.
 7           98.6     1270.
 8           98.6     1273.
 9           98.2     1902.
10           98.2     5373.
# ℹ 593 more rows</code></pre>
</div>
</div>
<section id="your-turn-4" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-4"><u><strong>Your Turn:</strong></u></h4>
<p>In the next code chunk, replace FinalGradeCEMS that is used with both the select() and arrange() functions with a different variable in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(course_id,TimeSpent)<span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(course_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 2
   course_id     TimeSpent
   &lt;chr&gt;             &lt;dbl&gt;
 1 PhysA-T116-01     2824.
 2 PhysA-T116-01     1289.
 3 PhysA-S216-01      719.
 4 PhysA-S216-01      719.
 5 PhysA-S216-01     1770.
 6 PhysA-S216-01     2322.
 7 PhysA-S216-01     4552.
 8 PhysA-S216-01     2415.
 9 PhysA-S216-01      610.
10 PhysA-S216-01       47 
# ℹ 593 more rows</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="explore" class="level2">
<h2 class="anchored" data-anchor-id="explore">3. Explore</h2>
<p>Exploratory data analysis, or exploring your data, involves processes of describing your data (such as by calculating the means and standard deviations of numeric variables, or counting the frequency of categorical variables) and, often, visualizing your data. As we’ll learn in later in this class, the explore phase can also involve the process of “feature engineering,” or creating new variables within a dataset [@krumm2018]. In this section, we’ll quickly pull together some basic stats using a handy function from the {skimr} package, and introduce you to a basic data visualization “code template” for the {ggplot} package from the tidyverse.</p>
<section id="summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h3>
<p>Let’s repurpose what we learned from our wrangle section to select just a few variables and quickly gather some descriptive stats using the skim() function from the {skimr} package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(FinalGradeCEMS,TimeSpent)<span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">select(sci_data, FinalGra…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FinalGradeCEMS</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">77.20</td>
<td style="text-align: right;">22.23</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">71.25</td>
<td style="text-align: right;">84.57</td>
<td style="text-align: right;">92.10</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: left;">▁▁▁▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">TimeSpent</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1799.75</td>
<td style="text-align: right;">1354.93</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">851.90</td>
<td style="text-align: right;">1550.91</td>
<td style="text-align: right;">2426.09</td>
<td style="text-align: right;">8870.88</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="your-turn-5" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-5"><u><strong>Your Turn:</strong></u></h4>
<p>Copy the code from the chunk from above and use it as a template to explore some other variables of interest from our sci_data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#use skim() to summarize other variables of your choosing.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(course_id,TimeSpent)<span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">select(sci_data, course_i…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">course_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TimeSpent</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1799.75</td>
<td style="text-align: right;">1354.93</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">851.9</td>
<td style="text-align: right;">1550.91</td>
<td style="text-align: right;">2426.09</td>
<td style="text-align: right;">8870.88</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>What happens if simply feed the skim function the entire sci_data object? Give it a try!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#use skim() on the entire data frame</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sci_data<span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">sci_data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">course_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">subject</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">semester</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">section</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gradebook_Item</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grade_Category</td>
<td style="text-align: right;">603</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: left;">:</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">student_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">86069.54</td>
<td style="text-align: right;">10548.60</td>
<td style="text-align: right;">43146.00</td>
<td style="text-align: right;">85612.50</td>
<td style="text-align: right;">88340.00</td>
<td style="text-align: right;">92730.50</td>
<td style="text-align: right;">97441.00</td>
<td style="text-align: left;">▁▁▁▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">total_points_possible</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4274.41</td>
<td style="text-align: right;">2312.74</td>
<td style="text-align: right;">840.00</td>
<td style="text-align: right;">2809.50</td>
<td style="text-align: right;">3583.00</td>
<td style="text-align: right;">5069.00</td>
<td style="text-align: right;">15552.00</td>
<td style="text-align: left;">▇▅▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_points_earned</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3244.69</td>
<td style="text-align: right;">1832.00</td>
<td style="text-align: right;">651.00</td>
<td style="text-align: right;">2050.50</td>
<td style="text-align: right;">2757.00</td>
<td style="text-align: right;">3875.00</td>
<td style="text-align: right;">12208.00</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">percentage_earned</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: left;">▁▁▃▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FinalGradeCEMS</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">77.20</td>
<td style="text-align: right;">22.23</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">71.25</td>
<td style="text-align: right;">84.57</td>
<td style="text-align: right;">92.10</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: left;">▁▁▁▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Points_Possible</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">76.87</td>
<td style="text-align: right;">167.51</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">935.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Points_Earned</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">68.63</td>
<td style="text-align: right;">145.26</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">26.12</td>
<td style="text-align: right;">828.20</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">q1</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">4.30</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▂▇▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">q2</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▂▆▇▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">q3</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▃▇▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">q4</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">4.27</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▂▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">q5</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▂▁▇▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">q6</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▃▇▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">q7</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▅▇▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">q8</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">4.29</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▂▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">q9</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">3.49</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▃▇▇▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">q10</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">4.10</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▂▃▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">TimeSpent</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1799.75</td>
<td style="text-align: right;">1354.93</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">851.90</td>
<td style="text-align: right;">1550.91</td>
<td style="text-align: right;">2426.09</td>
<td style="text-align: right;">8870.88</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TimeSpent_hours</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">22.58</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">14.20</td>
<td style="text-align: right;">25.85</td>
<td style="text-align: right;">40.43</td>
<td style="text-align: right;">147.85</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">TimeSpent_std</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-1.33</td>
<td style="text-align: right;">-0.70</td>
<td style="text-align: right;">-0.18</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">5.22</td>
<td style="text-align: left;">▇▅▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">int</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">3.90</td>
<td style="text-align: right;">4.20</td>
<td style="text-align: right;">4.70</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▃▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">pc</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▇▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uv</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3.33</td>
<td style="text-align: right;">3.67</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">▁▁▆▇▅</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="data-visualization" class="level3">
<h3 class="anchored" data-anchor-id="data-visualization">Data Visualization</h3>
<p>Data visualization is an extremely common practice in Learning Analytics, especially in the use of data dashboards. Data visualization involves graphically representing one or more variables with the goal of discovering patterns in data. These patterns may help us to answer research questions or generate new questions about our data, to discover relationships between and among variables, and to create or select features for data modeling.</p>
<p>In this section we’ll focus on using a basic code template for the {<a href="https://ggplot2.tidyverse.org/">ggplot2</a>} package from the tidyverse. ggplot2 is a system for declaratively creating graphics, based on <a href="https://ggplot2-book.org/introduction.html#what-is-the-grammar-of-graphics">the grammar of graphics</a> [@Wickham]. You provide the data, tell ggplot2 how to map variables to <a href="https://ggplot2.tidyverse.org/reference/aes.html">aesthetics</a>, what graphical elements to use, and it takes care of the details.</p>
</section>
<section id="the-graphing-workflow" class="level3">
<h3 class="anchored" data-anchor-id="the-graphing-workflow">The Graphing Workflow</h3>
<p>At it’s core, you can create some very simple but attractive graphs with just a couple lines of code. {<a href="https://ggplot2.tidyverse.org/">ggplot2</a>} follows the common workflow for making graphs. To make a graph, you simply:</p>
<ol type="1">
<li><p>Start the graph with ggplot() and include your data as an argument;</p></li>
<li><p>“Add” elements to the graph using the + operator a&nbsp;<a href="https://ggplot2.tidyverse.org/reference/#geoms">geom_() function</a>;</p></li>
<li><p>Select variables to graph on each axis with the aes() argument.</p>
<p>Let’s give it a try by creating a simple histogram of our FinalGradeCEMS variable. The code below creates a histogram, or a distribution of the values, in this case for students’ final grades.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sci_data)<span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>FinalGradeCEMS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 30 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rtutorial_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We won’t spend a lot of time on it in this case study, but you can also add a wide range of <a href="https://ggplot2.tidyverse.org/reference/index.html#aesthetics">aesthetic arguments</a> to each geom, like changing the color of the histogram bars by adding an argument to specify color. Let’s give that a try using the fill = argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sci_data)<span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>FinalGradeCEMS), <span class="at">fill=</span><span class="st">"Blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 30 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rtutorial_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="your-turn-6" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-6"><u><strong>Your Turn:</strong></u></h4>
<p>Now us the code chunk below to visualize the distribution of another variable in the data, specifically TimeSpent. Also, change the color to one of your choosing; consider this list of valid color names here: <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf" class="uri">http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a histogram of TimeSpent using a different color</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sci_data)<span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>TimeSpent), <span class="at">fill=</span><span class="st">"Aquamarine1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rtutorial_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">Scatterplots</h3>
<p>Let’s create a scatter plot for the relationship between these two variables. Scatterplots use the point geom, i.e., the geom_point() function, and are most useful for displaying the relationship between two continuous variables.</p>
<section id="your-turn-7" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-7"><u><strong>Your Turn:</strong></u></h4>
<p>Complete the code chunk below to create a simplet scatterplot with TimeSpent on the x axis and FinalGradeCEMS on the y axis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sci_data)<span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>TimeSpent, <span class="at">y=</span>FinalGradeCEMS))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 30 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rtutorial_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What do you think about the relationship between TimeSpent and FinalGradeCEMS?</p>
<ul>
<li>There does seem to be a correlation because students who spent more time studying typically did better on their final grade. There seems to be a clear diagonal line, and not students fall below it. However, extra time spent was not required to get a higher final grade because there are plenty of students who did well even with a lower time spent.</li>
</ul>
</section>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">4. Model</h2>
<p>“Model” is one of those terms that has many different meanings. For our purpose, we refer to the process of simplifying and summarizing our data. Thus, models can take many forms; calculating means represents a legitimate form of modeling data, as does estimating more complex models, including linear regressions, and models and algorithms associated with machine learning tasks. For now, we’ll run a base linear regression model to further examine the relationship between TimeSpent and FinalGradeCEMS.</p>
<p>We’ll dive much deeper into modeling in subsequent learning labs, but for now let’s see if there is a statistically significant relationship between students’ final grades, FinaGradeCEMS, and the TimeSpent on the course:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model_1<span class="ot">&lt;-</span><span class="fu">lm</span>(FinalGradeCEMS<span class="sc">~</span>TimeSpent, <span class="at">data =</span> sci_data)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FinalGradeCEMS ~ TimeSpent, data = sci_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-67.136  -7.805   4.723  14.471  30.317 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.581e+01  1.491e+00   44.13   &lt;2e-16 ***
TimeSpent   6.081e-03  6.482e-04    9.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.71 on 571 degrees of freedom
  (30 observations deleted due to missingness)
Multiple R-squared:  0.1335,    Adjusted R-squared:  0.132 
F-statistic: 87.99 on 1 and 571 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="your-turn-8" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-8"><u><strong>Your Turn:</strong></u></h4>
<p>Now let’s “add” <em>another</em> variable to the regression model. Specifically, use the + operator after TimeSpent to add the course subject variable, or another variable of your choosing, as a predictor of students’ final grades.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model_1<span class="ot">&lt;-</span><span class="fu">lm</span>(FinalGradeCEMS<span class="sc">~</span>TimeSpent<span class="sc">+</span>semester, <span class="at">data =</span> sci_data)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FinalGradeCEMS ~ TimeSpent + semester, data = sci_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-68.039  -7.442   4.962  14.592  30.359 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  67.6128776  1.7071997  39.605   &lt;2e-16 ***
TimeSpent     0.0060158  0.0006471   9.297   &lt;2e-16 ***
semesterS216 -4.0572474  1.7770965  -2.283   0.0228 *  
semesterT116  0.8319735  4.2202455   0.197   0.8438    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.64 on 569 degrees of freedom
  (30 observations deleted due to missingness)
Multiple R-squared:  0.142, Adjusted R-squared:  0.1375 
F-statistic: 31.39 on 3 and 569 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>What do you notice about the results? Add a comment or two below:</p>
<ul>
<li>We had slightly higher residuals and a drop of over 55 in the F-statistic. A quick search online told me that a higher F-statistic indicates a greater correlation between variables. Adding the semester variable caused a big drop which seems to indicates that what semester someone took a class did not impact their final grade as much as the time spent studying.</li>
</ul>
</section>
</section>
<section id="communicate" class="level2">
<h2 class="anchored" data-anchor-id="communicate">5. Communicate</h2>
<p>The final step in the workflow/process is sharing the results of your analysis with wider audience. Krumm et al.&nbsp;@krumm2018 have outlined the following 3-step process for communicating with education stakeholders findings from an analysis:</p>
<ol type="1">
<li><p><strong>Select.</strong> Communicating what one has learned involves selecting among those analyses that are most important and most useful to an intended audience, as well as selecting a form for displaying that information, such as a graph or table in static or interactive form, i.e.&nbsp;a “data product.”</p></li>
<li><p><strong>Polish</strong>. After creating initial versions of data products, research teams often spend time refining or polishing them, by adding or editing titles, labels, and notations and by working with colors and shapes to highlight key points.</p></li>
<li><p><strong>Narrate.</strong> Writing a narrative to accompany the data products involves, at a minimum, pairing a data product with its related research question, describing how best to interpret the data product, and explaining the ways in which the data product helps answer the research question and might be used to inform new analyses or a “change idea” for improving student learning.</p></li>
</ol>
<section id="render-file" class="level3">
<h3 class="anchored" data-anchor-id="render-file">Render File</h3>
<p>For your course project, you will have an opportunity to create a simple “data product” designed to illustrate some insights gained from your analysis and ideally highlight an action step or change idea that can be used to improve learning or the contexts in which learning occurs.For now, we will wrap up this work by converting our work into a webpage that can be used to communicate your learning and demonstrate some of your new R skills. To do so, you will need to “render” your document by clicking the Render button in the menu bar at that the top of this file. This will do two things; it will:</p>
<ol type="1">
<li><p>check through all your code for any errors; and,</p></li>
<li><p>create a file in your directory that you can use to share you work through <a href="https://posit.cloud/learn/guide#publish-from-cloud">Posit Cloud</a>, <a href="https://rpubs.com" title="RPubs">RPubs</a> , <a href="https://pages.github.com" title="GitHub Pages">GitHub Pages</a>, <a href="https://quartopub.com" title="Quarto Pub">Quarto Pub</a>, or other methods.</p></li>
</ol>
<p>Now that you’ve finished your first Rtutorial study, scroll back to the very top of this Quarto Document and change the author: “YOUR NAME HERE” to your actual name surrounded by quotation marks like so: author: “Dr.&nbsp;Cansu Tatar”.</p>
<section id="acknowledgement" class="level4">
<h4 class="anchored" data-anchor-id="acknowledgement">Acknowledgement:</h4>
<p>Special thanks to Dr.&nbsp;Shaun Kellogg for his support and guidance to create these course materials.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>